### ISSUE TITLE
Enumların ayrı dosyalar da tutulmalı

### ISSUE THREAD

**Issue by SeniorTurkmen** [asimolpiq/riverpod_session_management#2]
her enum kendine ait bir dosyada tutulmalı bu şekilde okuyan da karıştırır yazan da

```dart
enum TextEditingType {
  email,
  password,
}
```

**Comment by asimolpiq** [comment]
çözüldü

**Comment by SeniorTurkmen** [comment]
buralara hangi commitleri de linklersen daha iyi olur ilerisi için haberin olsun @asimolpiq
